// ui/web/src/components/ui/scroll-area.tsx
"use client"

import * as React from "react"
import { ScrollArea as ScrollAreaPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"

interface ScrollAreaProps
	extends React.ComponentProps<typeof ScrollAreaPrimitive.Root> {
	viewportRef?: React.Ref<HTMLDivElement>
}

function ScrollArea({
	className,
	children,
	viewportRef,
	...props
}: ScrollAreaProps) {
	return (
		<ScrollAreaPrimitive.Root
			data-slot="scroll-area"
			className={cn("relative", className)}
			{...props}
		>
			<ScrollAreaPrimitive.Viewport
				ref={viewportRef}
				data-slot="scroll-area-viewport"
				className="size-full rounded-[inherit] transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1"
			>
				{children}
			</ScrollAreaPrimitive.Viewport>
			<ScrollBar />
			<ScrollAreaPrimitive.Corner />
		</ScrollAreaPrimitive.Root>
	)
}

function ScrollBar({
	className,
	orientation = "vertical",
	...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>) {
	return (
		<ScrollAreaPrimitive.ScrollAreaScrollbar
			data-slot="scroll-area-scrollbar"
			orientation={orientation}
			className={cn(
				"flex touch-none p-px transition-colors select-none",
				orientation === "vertical" &&
					"h-full w-2.5 border-l border-l-transparent",
				orientation === "horizontal" &&
					"h-2.5 flex-col border-t border-t-transparent",
				className
			)}
			{...props}
		>
			<ScrollAreaPrimitive.ScrollAreaThumb
				data-slot="scroll-area-thumb"
				className="relative flex-1 rounded-full bg-border"
			/>
		</ScrollAreaPrimitive.ScrollAreaScrollbar>
	)
}

export { ScrollArea, ScrollBar }

// ui/web_legacy_backup_20260504/src/lib/components/ui/scroll-area/ScrollArea.svelte
<script>
	import { ScrollArea } from "bits-ui";
	import { cn } from "$lib/utils.js";

	let {
		orientation = "vertical",
		class: className,
		children,
		...restProps
	} = $props();
</script>

<ScrollArea.Root
	class={cn("relative overflow-hidden", className)}
	{...restProps}
>
	<ScrollArea.Viewport class="h-full w-full rounded-[inherit]">
		{@render children()}
	</ScrollArea.Viewport>
	<ScrollArea.Scrollbar
		{orientation}
		class={cn(
			"flex touch-none select-none transition-colors duration-150",
			orientation === "vertical" ? "h-full w-2 border-l border-l-transparent p-px" : "h-2 flex-col border-t border-t-transparent p-px",
		)}
	>
		<ScrollArea.Thumb
			class="relative flex-1 rounded-full bg-dl-text-dim/30 hover:bg-dl-text-dim/50 transition-colors"
		/>
	</ScrollArea.Scrollbar>
	<ScrollArea.Corner />
</ScrollArea.Root>
