// landing/src/lib/screener/Sparkline.svelte
<script lang="ts">
	/**
	 * 인라인 SVG sparkline — 결과 테이블 행에 가격 시계열 미니 차트.
	 * 시작점 대비 끝점이 양수면 녹색, 음수면 빨강, 0 이면 중립.
	 */

	interface Props {
		values: number[];
		width?: number;
		height?: number;
	}

	let { values, width = 60, height = 18 }: Props = $props();

	const path = $derived.by(() => {
		if (!values || values.length < 2) return null;
		const min = Math.min(...values);
		const max = Math.max(...values);
		const range = max - min || 1;
		const stepX = (width - 2) / (values.length - 1);
		const pad = 1;
		const points = values.map((v, i) => {
			const x = pad + i * stepX;
			const y = pad + (height - 2) * (1 - (v - min) / range);
			return `${x.toFixed(1)},${y.toFixed(1)}`;
		});
		return 'M' + points.join(' L');
	});

	const tone = $derived.by(() => {
		if (!values || values.length < 2) return 'neutral';
		const first = values[0];
		const last = values[values.length - 1];
		if (last > first * 1.005) return 'up';
		if (last < first * 0.995) return 'down';
		return 'neutral';
	});

	const stroke = $derived(tone === 'up' ? '#34d399' : tone === 'down' ? '#f87171' : '#94a3b8');
</script>

{#if path}
	<svg {width} {height} class="sparkline" aria-hidden="true">
		<path d={path} fill="none" stroke={stroke} stroke-width="1.4" stroke-linejoin="round" stroke-linecap="round" />
	</svg>
{:else}
	<span class="empty">—</span>
{/if}

<style>
	.sparkline {
		display: block;
	}
	.empty {
		font-size: 11px;
		color: #475569;
	}
</style>

// ui/web/src/features/dashboard/charts/Sparkline.tsx
// 카드 헤더용 mini sparkline — 경량 SVG path (recharts 의존 0).
// Koyfin 패턴 — last/value 옆 trend 한 줄.

interface Props {
	data: (number | null)[];
	width?: number;
	height?: number;
	color?: string;
	strokeWidth?: number;
}

export function Sparkline({
	data,
	width = 56,
	height = 16,
	color = 'currentColor',
	strokeWidth = 1.25,
}: Props) {
	const valid = data
		.map((v, i) => (v != null && Number.isFinite(v) ? { i, v } : null))
		.filter((x): x is { i: number; v: number } => x !== null);
	if (valid.length < 2) {
		return <svg width={width} height={height} aria-hidden />;
	}
	const xs = valid.map((p) => p.i);
	const ys = valid.map((p) => p.v);
	const xMin = Math.min(...xs);
	const xMax = Math.max(...xs);
	const yMin = Math.min(...ys);
	const yMax = Math.max(...ys);
	const xRange = xMax - xMin || 1;
	const yRange = yMax - yMin || 1;
	const pad = 1;
	const points = valid.map((p) => {
		const x = pad + ((p.i - xMin) / xRange) * (width - pad * 2);
		// SVG y flip (큰 값이 위로).
		const y = pad + (1 - (p.v - yMin) / yRange) * (height - pad * 2);
		return `${x.toFixed(1)},${y.toFixed(1)}`;
	});
	const path = `M ${points.join(' L ')}`;
	// last point dot.
	const last = points[points.length - 1].split(',');
	return (
		<svg
			width={width}
			height={height}
			viewBox={`0 0 ${width} ${height}`}
			style={{ color, display: 'block' }}
			aria-hidden
		>
			<path d={path} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" opacity={0.85} />
			<circle cx={last[0]} cy={last[1]} r={1.5} fill="currentColor" />
		</svg>
	);
}
