// landing/src/routes/dashboard/[stockCode]/sections/Sparkline.svelte
<script>
  // @ts-nocheck
  /** @type {{ data: number[], width?: number, height?: number, color?: string, fillOpacity?: number }} */
  let { data, width = 280, height = 64, color = '#fb923c', fillOpacity = 0.18 } = $props();

  const id = 'sg' + Math.random().toString(36).slice(2, 8);

  const min = $derived(Math.min(...data));
  const max = $derived(Math.max(...data));
  const range = $derived((max - min) || 1);
  const pad = 4;
  const w = $derived(width - pad * 2);
  const h = $derived(height - pad * 2);
  const step = $derived(w / (data.length - 1));

  const pts = $derived(
    data.map((v, i) => [pad + i * step, pad + h - ((v - min) / range) * h])
  );
  const line = $derived(
    pts.map((p, i) => (i === 0 ? `M ${p[0]} ${p[1]}` : `L ${p[0]} ${p[1]}`)).join(' ')
  );
  const area = $derived(
    line + ` L ${pts[pts.length - 1][0]} ${pad + h} L ${pad} ${pad + h} Z`
  );
  const last = $derived(pts[pts.length - 1]);
</script>

<svg width="100%" viewBox="0 0 {width} {height}" style="display:block">
  <defs>
    <linearGradient id={id} x1="0" x2="0" y1="0" y2="1">
      <stop offset="0%" stop-color={color} stop-opacity={fillOpacity} />
      <stop offset="100%" stop-color={color} stop-opacity="0" />
    </linearGradient>
  </defs>
  <path d={area} fill="url(#{id})" />
  <path d={line} fill="none" stroke={color} stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
  <circle cx={last[0]} cy={last[1]} r="3" fill={color} stroke="#0f1219" stroke-width="1.5" />
</svg>

// ui/web/src/features/dashboard/charts/Sparkline.tsx
// 카드 헤더용 mini sparkline — 경량 SVG path (recharts 의존 0).
// Koyfin 패턴 — last/value 옆 trend 한 줄.

interface Props {
	data: (number | null)[];
	width?: number;
	height?: number;
	color?: string;
	strokeWidth?: number;
}

export function Sparkline({
	data,
	width = 56,
	height = 16,
	color = 'currentColor',
	strokeWidth = 1.25,
}: Props) {
	const valid = data
		.map((v, i) => (v != null && Number.isFinite(v) ? { i, v } : null))
		.filter((x): x is { i: number; v: number } => x !== null);
	if (valid.length < 2) {
		return <svg width={width} height={height} aria-hidden />;
	}
	const xs = valid.map((p) => p.i);
	const ys = valid.map((p) => p.v);
	const xMin = Math.min(...xs);
	const xMax = Math.max(...xs);
	const yMin = Math.min(...ys);
	const yMax = Math.max(...ys);
	const xRange = xMax - xMin || 1;
	const yRange = yMax - yMin || 1;
	const pad = 1;
	const points = valid.map((p) => {
		const x = pad + ((p.i - xMin) / xRange) * (width - pad * 2);
		// SVG y flip (큰 값이 위로).
		const y = pad + (1 - (p.v - yMin) / yRange) * (height - pad * 2);
		return `${x.toFixed(1)},${y.toFixed(1)}`;
	});
	const path = `M ${points.join(' L ')}`;
	// last point dot.
	const last = points[points.length - 1].split(',');
	return (
		<svg
			width={width}
			height={height}
			viewBox={`0 0 ${width} ${height}`}
			style={{ color, display: 'block' }}
			aria-hidden
		>
			<path d={path} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" opacity={0.85} />
			<circle cx={last[0]} cy={last[1]} r={1.5} fill="currentColor" />
		</svg>
	);
}
