// ui/web/src/features/dashboard/charts/Sparkline.tsx
// 카드 헤더용 mini sparkline — 경량 SVG path (recharts 의존 0).
// Koyfin 패턴 — last/value 옆 trend 한 줄.

interface Props {
	data: (number | null)[];
	width?: number;
	height?: number;
	color?: string;
	strokeWidth?: number;
}

export function Sparkline({
	data,
	width = 56,
	height = 16,
	color = 'currentColor',
	strokeWidth = 1.25,
}: Props) {
	const valid = data
		.map((v, i) => (v != null && Number.isFinite(v) ? { i, v } : null))
		.filter((x): x is { i: number; v: number } => x !== null);
	if (valid.length < 2) {
		return <svg width={width} height={height} aria-hidden />;
	}
	const xs = valid.map((p) => p.i);
	const ys = valid.map((p) => p.v);
	const xMin = Math.min(...xs);
	const xMax = Math.max(...xs);
	const yMin = Math.min(...ys);
	const yMax = Math.max(...ys);
	const xRange = xMax - xMin || 1;
	const yRange = yMax - yMin || 1;
	const pad = 1;
	const points = valid.map((p) => {
		const x = pad + ((p.i - xMin) / xRange) * (width - pad * 2);
		// SVG y flip (큰 값이 위로).
		const y = pad + (1 - (p.v - yMin) / yRange) * (height - pad * 2);
		return `${x.toFixed(1)},${y.toFixed(1)}`;
	});
	const path = `M ${points.join(' L ')}`;
	// last point dot.
	const last = points[points.length - 1].split(',');
	return (
		<svg
			width={width}
			height={height}
			viewBox={`0 0 ${width} ${height}`}
			style={{ color, display: 'block' }}
			aria-hidden
		>
			<path d={path} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" opacity={0.85} />
			<circle cx={last[0]} cy={last[1]} r={1.5} fill="currentColor" />
		</svg>
	);
}

// landing/src/lib/components/ui/Sparkline.svelte
<script lang="ts">
	/** 미니 sparkline — pure SVG, no deps. mono color, smooth curve. */
	interface Props {
		data: (number | null | undefined)[];
		width?: number;
		height?: number;
		stroke?: string;
		fill?: string;
		showDots?: boolean;
		smooth?: boolean;
	}

	let {
		data = [],
		width = 120,
		height = 36,
		stroke = 'currentColor',
		fill = 'none',
		showDots = false,
		smooth = true
	}: Props = $props();

	const cleaned = $derived(data.map((v) => (typeof v === 'number' && Number.isFinite(v) ? v : null)));

	const stats = $derived.by(() => {
		const valid = cleaned.filter((v): v is number => v != null);
		if (valid.length === 0) return { min: 0, max: 1 };
		const min = Math.min(...valid);
		const max = Math.max(...valid);
		return { min, max: max === min ? min + 1 : max };
	});

	const pad = 2;
	const points = $derived.by(() => {
		const w = width - pad * 2;
		const h = height - pad * 2;
		const range = stats.max - stats.min;
		return cleaned.map((v, i) => {
			if (v == null) return null;
			const x = pad + (i / Math.max(cleaned.length - 1, 1)) * w;
			const y = pad + (1 - (v - stats.min) / range) * h;
			return [x, y] as [number, number];
		});
	});

	const path = $derived.by(() => {
		const valid = points.filter(
			(p): p is [number, number] =>
				p != null && Number.isFinite(p[0]) && Number.isFinite(p[1])
		);
		if (valid.length < 2) return '';
		if (!smooth || valid.length < 3) {
			return valid.map(([x, y], i) => (i === 0 ? `M ${x} ${y}` : `L ${x} ${y}`)).join(' ');
		}
		// Catmull-Rom → Bézier (smooth)
		let d = `M ${valid[0][0]} ${valid[0][1]}`;
		for (let i = 0; i < valid.length - 1; i++) {
			const p0 = valid[i - 1] ?? valid[i];
			const p1 = valid[i];
			const p2 = valid[i + 1];
			const p3 = valid[i + 2] ?? p2;
			const cp1x = p1[0] + (p2[0] - p0[0]) / 6;
			const cp1y = p1[1] + (p2[1] - p0[1]) / 6;
			const cp2x = p2[0] - (p3[0] - p1[0]) / 6;
			const cp2y = p2[1] - (p3[1] - p1[1]) / 6;
			d += ` C ${cp1x} ${cp1y}, ${cp2x} ${cp2y}, ${p2[0]} ${p2[1]}`;
		}
		return d;
	});
</script>

<svg viewBox="0 0 {width} {height}" {width} {height} class="spark" role="img" aria-hidden="true">
	{#if path}
		<path d={path} {stroke} stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" {fill} />
		{#if showDots}
			{#each points as p}
				{#if p}
					<circle cx={p[0]} cy={p[1]} r="2" {fill} stroke="none" />
				{/if}
			{/each}
		{/if}
	{/if}
</svg>

<style>
	.spark { display: inline-block; vertical-align: middle; }
</style>
